apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: b
          image: ahmedba77777/backend7
          imagePullPolicy: Always  # Ensure that Kubernetes always pulls the latest image
          ports:
            - containerPort: 3000
          env:
            - name: MYSQL_PASSWORD
              value: "password"
            - name: MYSQL_USER
              value: "user2"
            - name: MYSQL_HOST
              value: "mysql"
            - name: MYSQL_DATABASE
              value: "employeems"
